---
title: "**Presentación**"
--- 
<br>
<br>
<br>

<div class=text-justify>

# **Resultados de la Prueba Piloto de la Encuesta de Residuos de Alimentos y Materia Orgánica, 2020**
 
<br>
<br>
<br>
 
## Objetivo general del proyecto

<br>

Presentar los resultados del levantamiento de la Prueba Piloto de la Encuesta de Residuos de Alimentos y Materia Orgánica 2020 (ERAMO 2020), que la Dirección de Estadísticas del Medio Ambiente del INEGI, en coordinación con universidades e instituciones de educación superior de varios estados de la República, llevaron a cabo del 3 noviembre al 11 de diciembre del 2020.

<br>
<br>

## Objetivos Específicos:

<br>

1. Conformar dentro de una arquitectura de base de datos relacional (db) los datos captados en campo provenientes del levantamiento de la prueba piloto mencionada, de modo que dicha estructura de datos pueda ser fácilmente explotable.

2. Validar los datos para generar una base de datos confiable, con la suficiente consistencia lógica entre variables, programando reglas de validación específicas que permitan solucionar las incongruencias que puedan existir en los datos.

3. Realizar la explotación de la información a través de la generación de algunos indicadores de relevancia para la encuesta.

4. Permitir a los usuarios descargar las bases de datos de la prueba piloto, para sus propios análisis.


<br>
<br>


## Descripción de la ERAMO

<br>


Las pérdidas de alimentos que se producen a lo largo de la cadena desde la cosecha, el sacrificio o la captura hasta el nivel minorista, pero sin incluirlo. El desperdicio de alimentos se produce en el nivel de la venta al por menor y el consumo.

Un tercio estimado de toda la comida se pierde o se desperdicia al pasar de donde se produce a donde se consume; teniendo importantes impactos económicos, sociales y ambientales.

Las causas son variadas y van desde el momento inadecuado de cosecha, las condiciones climáticas, las prácticas aplicadas en la cosecha, su manipulación, el transporte y almacenamiento, hasta las dificultades en la comercialización de los productos.

Actualmente, se están realizando esfuerzos por parte de la FAO y ONU Medio Ambiente para medir el progreso hacia el logro del ODS 12.3 a través de dos índices separados: el Índice de Pérdida de Alimentos (FLI), dirigido por la FAO; y el Índice de desperdicio de alimentos (FWI), liderado por ONU Medio Ambiente  [(http://www.fao.org/platform-food-loss-waste/background/en/)](http://www.fao.org/platform-food-loss-waste/background/en/){target="_blank_"}.

En  México no existe estadística oficial sobre la pérdida y desperdicio de alimentos (PDA). Algunos estudios hacen medición o estimación del desperdicio y pérdida de los alimentos, pero requieren de un respaldo estadístico de mayor envergadura, en un esfuerzo nacional que recupere las distintas realidades de nuestro vasto territorio y diversidad cultural.

Por ello, desde el año pasado, se constituyó un grupo de trabajo denominado *Grupo Interinstitucional de Expertos en Pérdida y Desperdicio de Alimentos*, con la finalidad de diseñar una encuesta sobre residuos alimenticios dirigida a toda la cadena alimentaria, a fin de conocer su origen, cantidad, composición, reutilización, tratamiento y disposición final; con el propósito de generar información valiosa para conocer el fenómeno y facilitar, en lo posible, la toma de decisiones técnicamente sustentada. 

Dicho grupo se integra por representantes de las siguientes instituciones:

- Centro de Estudios para el Desarrollo Rural Sustentable y la Soberanía Alimentaria (CEDRSSA), adscrito a la Cámara de Diputados

- Instituto Politécnico Nacional (IPN)

- Secretaría del Medio Ambiente y Recursos Naturales

- Universidad Autónoma Chapingo

- Universidad Autónoma Agraria "Antonio Narro"

- Oficina de Consultoría del Banco Mundial para la PDA en México

- INEGI

En conjunto, se ha trabajado hasta el momento en la construcción de un marco conceptual y metodológico que sirva a los objetivos trazados, mismo que retoma los marcos teóricos que ha desarrollado la FAO y la Comisión de Cooperación Ambiental de América del Norte, para adaptarlos a la realidad de México.

En este contexto a fines del 2020 se llevó a cabo el levantamiento de la prueba piloto de la ERAMO a fines del 2020. La recolección de los datos en campo ha sido realizado por los participantes voluntarios y alumnos de instituciones académicas que forman parte de la [RED 12.3 PDA México](http://red123pda.org.mx/#/){target="_blank_"}, o que estudian el fenómeno de la pérdida y desperdicio de alimentos desde alguna de sus dimensiones e implicaciones (económica, social, ambiental, cultural).[^1^]. 

[^1^]: La Red 12.3 PDA México es una organización basada en un grupo de trabajo multidisciplinario de investigadores con instituciones tanto públicas como privadas, tecnólogos, empresarios y organizaciones, para contribuir a la sustentabilidad de las cadenas de suministro de alimentos, a través de diseñar, establecer y evaluar estrategias, tanto tecnológicas como de innovación social, que conduzcan a reducir la pérdida y desperdicio de alimentos en México.

El INEGI, a través de la Dirección de Estadísticas del Medio Ambiente, funcionó como coordinador general del operativo, así como institución encargada de integrar, validar, procesar y presentar resultados de la prueba piloto, y finalmente, entregar la base de datos liberada para su análisis y explotación a los participantes y colaboradores del proyecto. Las instituciones participantes en el levantamiento fueron las siguientes:

- Instituto Polítécnico Nacional

- Universidad Autónoma Chapingo (Campus Central y URUSSE Tabasco)

- Universidad de Ciencias y Artes de Chiapas

- Tecnológico Nacional de México en Celaya

- Universidad Autónoma Agraria “Antonio Narro”

- Colegio de Postgraduados Campus Veracruz

- Centro de Investigación y Asistencia en Tecnología y Diseño del Estado de Jalisco

- Universidad Autónoma de Nuevo León (Facultad de Ciencias Biológicas)

- Universidad Autónoma de Chihuahua

- Universidad Autónoma de Coahuila

- Universidad Autónoma de Zacatecas
 
- Universidad Autónoma del Estado de Hidalgo

- Universidad Politécnica de Victoria

- Universidad Autónoma de Baja California


Cabe aclarar que la muestra utilizada en el operativo, al haber sido seleccionada por conveniencia o por cuotas (muestra dirigida a productores agropecuarios y establecimientos conocidos o con ubicaciones accesibles a los entrevistadores) **no es por supuesto una muestra probabilística**, por lo que sus resultados no tienen representatividad estadística, y pueden servir únicamente para efectos de análisis, tendencias, y exploración del comportamiento del fenómeno en las unidades de producción observadas.

Las unidades de observación fueron unidades de producción agropecuaria y  establecimientos de los sectores de manufactura, distribución, transporte y servicios relacionados con alimentos. 

<br>
<br>




<br>
 